/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-02-03 01:31:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   
    if (session == null || session.getAttribute("userEmail") == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    String userEmail = (String) session.getAttribute("userEmail");
    String userName  = (String) session.getAttribute("userName");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Dashboard | CampusExchange</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<!-- NAVBAR -->\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div class=\"nav-left\">CampusExchange</div>\r\n");
      out.write("    <div class=\"nav-right\">\r\n");
      out.write("        <a href=\"dashboard.jsp\">Dashboard</a>\r\n");
      out.write("        <a href=\"buy.jsp\">Buy</a>\r\n");
      out.write("        <a href=\"sell.jsp\">Sell</a>\r\n");
      out.write("        <a href=\"rent.jsp\">Rent</a>\r\n");
      out.write("        <a href=\"donate.jsp\">Donate</a>\r\n");
      out.write("        <a href=\"logout\">Logout</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- HERO -->\r\n");
      out.write("<div class=\"dashboard-hero\">\r\n");
      out.write("    <h1>Welcome back ");
      out.print( userName );
      out.write("</h1>\r\n");
      out.write("    <p>Logged in as <strong>");
      out.print( userEmail );
      out.write("</strong></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- QUICK ACTIONS -->\r\n");
      out.write("<div class=\"quick-actions\">\r\n");
      out.write("    <h2>What would you like to do?</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dashboard-actions\">\r\n");
      out.write("        <a href=\"buy.jsp\" class=\"action-card\">\r\n");
      out.write("            <h3>Buy Items</h3>\r\n");
      out.write("            <p>Find books, gadgets & essentials from students</p>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"sell.jsp\" class=\"action-card\">\r\n");
      out.write("            <h3>Sell Items</h3>\r\n");
      out.write("            <p>Post items you no longer need</p>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"rent.jsp\" class=\"action-card\">\r\n");
      out.write("            <h3>Rent Items</h3>\r\n");
      out.write("            <p>Rent items for short-term use</p>\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"donate.jsp\" class=\"action-card\">\r\n");
      out.write("            <h3>Donate Items</h3>\r\n");
      out.write("            <p>Help others by donating unused items</p>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"myItems.jsp\" class=\"dash-card\">\r\n");
      out.write("    <h3>My Items</h3>\r\n");
      out.write("    <p>Manage your listings</p>\r\n");
      out.write("</a>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- HOW IT WORKS -->\r\n");
      out.write("<div class=\"how-it-works\">\r\n");
      out.write("    <h2>How CampusExchange Works</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"steps\">\r\n");
      out.write("        <div class=\"step-box\">\r\n");
      out.write("            <h3>1. Post or Browse</h3>\r\n");
      out.write("            <p>Sell, rent or donate items — or browse what others posted.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"step-box\">\r\n");
      out.write("            <h3>2. Connect</h3>\r\n");
      out.write("            <p>Connect directly with students within your campus.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"step-box\">\r\n");
      out.write("            <h3>3. Exchange</h3>\r\n");
      out.write("            <p>Buy, rent or receive items safely and easily.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- FOOTER CTA -->\r\n");
      out.write("<div class=\"dashboard-footer\">\r\n");
      out.write("    <h2>Have something to share?</h2>\r\n");
      out.write("    <p>Turn unused items into value or help someone today.</p>\r\n");
      out.write("    <a href=\"sell.jsp\" class=\"footer-btn\">Post an Item</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
