/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-02-02 03:56:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>CampusExchange</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- NAVBAR -->\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <a href=\"index.jsp\">Home</a>\r\n");
      out.write("    <a href=\"register.jsp\">Register</a>\r\n");
      out.write("    <a href=\"login.jsp\">Login</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- HERO -->\r\n");
      out.write("<div class=\"hero\">\r\n");
      out.write("    <h1>CampusExchange</h1>\r\n");
      out.write("    <p>\r\n");
      out.write("        A secure and trusted marketplace designed exclusively for students\r\n");
      out.write("        to buy, sell, rent, or donate items within their campus community.\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cta\">\r\n");
      out.write("        <a href=\"login.jsp\">Get Started</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- FEATURES -->\r\n");
      out.write("<div class=\"features\">\r\n");
      out.write("    <h2>What You Can Do</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"feature-grid\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("            <h3>Buy</h3>\r\n");
      out.write("            <p>Purchase books, gadgets, and essentials directly from fellow students.</p>\r\n");
      out.write("            <a href=\"login.jsp\">Explore Buy →</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fa fa-tags\"></i>\r\n");
      out.write("            <h3>Sell</h3>\r\n");
      out.write("            <p>Sell unused items safely within your campus without middlemen.</p>\r\n");
      out.write("            <a href=\"login.jsp\">Start Selling →</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fa fa-home\"></i>\r\n");
      out.write("            <h3>Rent</h3>\r\n");
      out.write("            <p>Rent calculators, cycles, rooms, and more for short-term needs.</p>\r\n");
      out.write("            <a href=\"login.jsp\">View Rentals →</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"feature-card\">\r\n");
      out.write("            <i class=\"fa fa-heart\"></i>\r\n");
      out.write("            <h3>Donate</h3>\r\n");
      out.write("            <p>Help juniors and peers by donating items you no longer need.</p>\r\n");
      out.write("            <a href=\"login.jsp\">Donate Now →</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- INFO -->\r\n");
      out.write("<div class=\"info\">\r\n");
      out.write("    <h2>Why CampusExchange?</h2>\r\n");
      out.write("    <p>\r\n");
      out.write("        CampusExchange is built to promote sustainability, affordability,\r\n");
      out.write("        and trust among students. By keeping transactions within the campus,\r\n");
      out.write("        we ensure safety, transparency, and meaningful peer connections.\r\n");
      out.write("    </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- FOOTER -->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    © 2026 CampusExchange | Built for Students\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
