/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-02-02 17:00:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import com.campusexchange.db.DBConnection;

public final class itemDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.campusexchange.db.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // ===== SESSION CHECK =====
    HttpSession sess = request.getSession(false);
    if (sess == null || sess.getAttribute("userEmail") == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    String userEmail = (String) sess.getAttribute("userEmail");
    String itemIdStr = request.getParameter("id");

    if (itemIdStr == null) {
        response.sendRedirect("buy.jsp");
        return;
    }

    int itemId = Integer.parseInt(itemIdStr);
    Connection con = DBConnection.getConnection();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Item Details - CampusExchange</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- NAVBAR -->\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <a href=\"dashboard.jsp\">Dashboard</a>\r\n");
      out.write("    <a href=\"buy.jsp\">Buy</a>\r\n");
      out.write("    <a href=\"sell.jsp\">Sell</a>\r\n");
      out.write("    <a href=\"rent.jsp\">Rent</a>\r\n");
      out.write("    <a href=\"donate.jsp\">Donate</a>\r\n");
      out.write("    <a href=\"logout\">Logout</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    PreparedStatement ps = con.prepareStatement(
        "SELECT * FROM items WHERE id=?"
    );
    ps.setInt(1, itemId);
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {

        String sellerEmail = rs.getString("seller_email");
        String status = rs.getString("status"); // AVAILABLE / SOLD

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"auth-container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- IMAGE -->\r\n");
      out.write("    <img src=\"uploads/");
      out.print( rs.getString("image") );
      out.write("\"\r\n");
      out.write("         style=\"width:100%; max-height:300px; object-fit:cover; border-radius:10px;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- DETAILS -->\r\n");
      out.write("    <h2>");
      out.print( rs.getString("title") );
      out.write("</h2>\r\n");
      out.write("    <p>");
      out.print( rs.getString("description") );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"price\">₹ ");
      out.print( rs.getDouble("price") );
      out.write("</p>\r\n");
      out.write("    <p>Seller: <strong>");
      out.print( sellerEmail );
      out.write("</strong></p>\r\n");
      out.write("\r\n");
      out.write("    <p>\r\n");
      out.write("        Status:\r\n");
      out.write("        <strong style=\"color:");
      out.print( "SOLD".equals(status) ? "red" : "green" );
      out.write("\">\r\n");
      out.write("            ");
      out.print( status );
      out.write("\r\n");
      out.write("        </strong>\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <hr style=\"margin:20px 0;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- STATUS MESSAGES -->\r\n");
      out.write("    ");

        if ("1".equals(request.getParameter("success"))) {
    
      out.write("\r\n");
      out.write("        <p style=\"color:green; text-align:center; font-weight:600;\">\r\n");
      out.write("            ✔ Interest sent successfully\r\n");
      out.write("        </p>\r\n");
      out.write("    ");

        }
        if ("already".equals(request.getParameter("success"))) {
    
      out.write("\r\n");
      out.write("        <p style=\"color:#b35a00; text-align:center; font-weight:600;\">\r\n");
      out.write("            ⚠ You already showed interest\r\n");
      out.write("        </p>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- SELLER VIEW -->\r\n");
      out.write("    ");

        if (userEmail.equals(sellerEmail)) {
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <p style=\"color:#7b1e3a; font-weight:bold; text-align:center;\">\r\n");
      out.write("            You posted this item\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <h3 style=\"margin-top:20px;\">Interested Students</h3>\r\n");
      out.write("\r\n");
      out.write("        ");

            PreparedStatement psReq = con.prepareStatement(
                "SELECT buyer_email FROM item_requests WHERE item_id=?"
            );
            psReq.setInt(1, itemId);
            ResultSet rsReq = psReq.executeQuery();

            boolean found = false;
            while (rsReq.next()) {
                found = true;
        
      out.write("\r\n");
      out.write("                <p>📧 ");
      out.print( rsReq.getString("buyer_email") );
      out.write("</p>\r\n");
      out.write("        ");

            }

            if (!found) {
        
      out.write("\r\n");
      out.write("                <p style=\"color:gray;\">No interest yet</p>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- MARK AS SOLD -->\r\n");
      out.write("        ");

            if ("AVAILABLE".equals(status)) {
        
      out.write("\r\n");
      out.write("            <form action=\"markSold\" method=\"post\" style=\"margin-top:20px;\">\r\n");
      out.write("                <input type=\"hidden\" name=\"itemId\" value=\"");
      out.print( itemId );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn-primary\" style=\"background:#444;\">\r\n");
      out.write("                    Mark as Sold\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- BUYER VIEW -->\r\n");
      out.write("    ");

        } else {

            if ("SOLD".equals(status)) {
    
      out.write("\r\n");
      out.write("            <p style=\"color:red; text-align:center; font-weight:600;\">\r\n");
      out.write("                ❌ This item is already sold\r\n");
      out.write("            </p>\r\n");
      out.write("    ");

            } else {

                PreparedStatement chkPs = con.prepareStatement(
                    "SELECT 1 FROM item_requests WHERE item_id=? AND buyer_email=?"
                );
                chkPs.setInt(1, itemId);
                chkPs.setString(2, userEmail);
                ResultSet chkRs = chkPs.executeQuery();

                if (chkRs.next()) {
    
      out.write("\r\n");
      out.write("                    <button class=\"btn-primary\"\r\n");
      out.write("                            style=\"opacity:0.6; cursor:not-allowed;\" disabled>\r\n");
      out.write("                        Interest Sent ✔\r\n");
      out.write("                    </button>\r\n");
      out.write("    ");

                } else {
    
      out.write("\r\n");
      out.write("                    <form action=\"interest\" method=\"post\" style=\"text-align:center;\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"itemId\" value=\"");
      out.print( itemId );
      out.write("\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn-primary\">\r\n");
      out.write("                            I'm Interested\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </form>\r\n");
      out.write("    ");

                }
            }
        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

    } else {

      out.write("\r\n");
      out.write("    <p style=\"text-align:center;\">Item not found</p>\r\n");

    }

    con.close();

      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
